from django.urls import path
from django.contrib.auth import views as auth_views


from . import views

urlpatterns = [
    path('',views.home,name='home'),
    path('leave/',views.leave,name ='leave'),
    path('login/',views.loginPage,name="login"),
    path('register/',views.registerPage,name="register"),
    path('logout/',views.logoutUser,name="logout"),
    path('profile/', views.profileSettings, name="profile"),
    path('input/',views.input,name='input'),
    path('status/',views.status,name='status'),
    path('policy/',views.policy,name='policy'),
    path('policy/<slug:slug>/',views.policyview,name='policyview'),
    path('analytics/',views.analytics,name='analytics'),
    path('demo/', views.demo, name='demo'),
    path('teams/', views.teams, name='teams'),
    path('calender/', views.calender, name='calender'),
    path('events/', views.events, name='events'),
    path('custom_events/', views.custom_events, name='custom_events'),
    path('task/', views.task, name='task'),
    path('tasks_display/', views.tasks_display, name='tasks_display'),
    path('task_view/<int:pid>', views.task_view, name='task_view'),
    path('task_agree/<int:pid>', views.task_agree, name='task_agree'),
    path('task_finish/<int:pid>', views.task_finish, name='task_finish'),
    path('ajax/load-persons/', views.ajax_load_persons, name='ajax_load_persons'),
    path('admin_view/', views.admin_view, name='admin_view'),
    path('ticket/', views.ticket, name='ticket'),
    path('ticket_display/', views.ticket_display, name='ticket_display'),
    path('ticket_view/<int:pid>', views.ticket_view, name='ticket_view'),
    path('mytickets/', views.mytickets, name='mytickets'),
    path('end_ticket/<int:pid>', views.end_ticket, name='end_ticket'),
    path('end_process/<int:pid>',views.end_process,name='end_process'),
    path('pro_analysis/<int:pid>',views.pro_analysis,name='pro_analysis'),
    path('create_org/<int:pid>', views.create_org, name='create_org'),
    path('create_org/', views.create_org, name='2'),

    # path('orgchart/', views.orgchart, name='orgchart'),
    path('user_info/<int:id>', views.user_info, name='user_info'),
    path('overtime_events/', views.overtime_events, name='overtime_events'),
    path('select_overtime/', views.select_overtime, name='select_overtime'),
    path('ajax/load-overtime/', views.ajax_load_overtime, name='ajax_load_overtime'),
    path('clientregisterPage/',views.clientregisterPage,name="clientregister"),
    path('myleaves/',views.myleaves,name='myleaves'),
    path('leaveslist/',views.leaveslist,name='leaveslist'),
    path('approve_leave/<int:id>',views.approve_leave,name='approve_leave'),
    path('disapprove_leave/<int:id>',views.disapprove_leave,name='disapprove_leave'),
    path('salary/',views.salary,name='salary'),

    path('myovertime/',views.myovertimes,name='myovertime'),
    path('overtimelist/',views.overtimelist,name='overtimelist'),
    path('approve_overtime/<int:id>',views.approve_overtime,name='approve_overtime'),
    path('disapprove_overtime/<int:id>',views.disapprove_overtime,name='disapprove_overtime'),
    path('orgchart',views.abc,name='abc'),
    path('policy_admin/',views.policy_admin,name='policy_admin'),
]